version: '3'
services:
    app:
        image: 'nginx'
        expose:
            - '5000'
        volumes:
            - ./app/html:/usr/share/nginx/html
    lb:
        image: 'nginx'
        ports:
            - '80:80'
        volumes:
            - ./lb/nginx.conf:/etc/nginx/nginx.conf
        links:
            - app
